apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: networking.workloads-infrastructure.tenantn
  namespace: hierarchy
spec:
  displayName: tenantN
  folderRef:
    name: networking.workloads-infrastructure
