apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: networking.workloads-infrastructure.tenant1
  namespace: hierarchy
spec:
  displayName: tenant1
  folderRef:
    name: networking.workloads-infrastructure
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: networking.workloads-infrastructure.tenant1.pbmm
  namespace: hierarchy
spec:
  displayName: PBMM
  folderRef:
    name: networking.workloads-infrastructure.tenant1
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: networking.workloads-infrastructure.tenant1.unclass
  namespace: hierarchy
spec:
  displayName: Unclass
  folderRef:
    name: networking.workloads-infrastructure.tenant1